version: '3.5'

networks:
   skynet:

volumes:
   elasticsearch-data: {}

services:

   elasticsearch:
      build:
         context: elasticsearch/
      hostname: elasticsearch
      container_name: elasticsearch
      volumes:
         - elasticsearch-data:/usr/share/elasticsearch/data
      restart: unless-stopped
      environment:
         ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ports:
         - 9200:9200
         - 9300:9300
      networks:
         - skynet

   logstash:
      build:
         context: logstash/
      container_name: logstash
      environment:
         LS_JAVA_OPTS: "-Xmx256m -Xms256m"
         EVENT_HUB_CONNECTION: $EVENT_HUB_CONNECTION
         CONSUMER_GROUP: $CONSUMER_GROUP
         STORAGE_CONNECTION: $STORAGE_CONNECTION
      networks:
         - skynet

   kibana:
      build:
         context: kibana/
      hostname: kibana
      container_name: kibana
      restart: unless-stopped
      ports:
         - 5601:5601
      networks:
         - skynet
      depends_on:
         - elasticsearch
